# Example file for running the exporter from a local build
version: "3.8"
services:
  fritz-exporter:
    image: fritz_exporter:local
    build: ../
    container_name: fritz-exporter
    restart: always
    environment:
      FRITZ_HOSTNAME: 'fritz.box'
      FRITZ_USERNAME: 'prometheus'
      FRITZ_PASSWORD: 'prompassword'
    ports:
      - "9787:9787"
