# Example file for running the exporter from a local build
version: "3.8"
services:
  fritz-exporter:
    image: fritz_exporter:local
    build: ../
    container_name: fritz-exporter
    restart: always
    environment:
      FRITZ_EXPORTER_CONFIG: 'fritz.box,prometheus,prompassword,repeater01,prometheus,prompassword'
    ports:
      - "9787:9787"