name: Build Dev Docker image

on:
  push:
    branches:
    - develop

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      if: success()
      run: |
        image=ghcr.io/pdreker/fritz_exporter
        tag=develop
        echo ${{ secrets.GHCR_PAT }} | docker login -u pdreker --password-stdin ghcr.io
        docker build -t $image:$tag .
        docker push $image:$tag