name: Build Docker image

on:
  push:
    branches:
    - master

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    name: Get SemVer from Labels
    steps:
    - name: Get PR labels
      id: pr-labels
      uses: joerick/pr-labels-action@v1.0.6
    - id: trim-label
      if: contains(steps.pr-labels.outputs.labels, ' semver_'
      run: |
        echo -n "::set-outpute name=bump::$(echo ${{ steps.pr-labels.outputs.labels }} | sed -r -e 's/ semver_([a-zA-Z0-9]+) /\1/')
    - id: get-version
      uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ steps.trim-label.outputs.bump }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
  
  build-docker:
    runs-on: ubuntu-latest
    needs: get-version
    name: Build Docker Image
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      if: success()
      run: |
        image=ghcr.io/pdreker/fritzbox_exporter
        semver=${{ needs.get-version.outputs.version }}
        echo ${{ secrets.GHCR_PAT }} | docker login -u pdreker --password-stdin ghcr.io
        docker build -t $image:$semver .
        docker push $image:semver
