name: Build Docker image

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Update SemVer
        id: update_semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2

      - name: Build Docker Image
        if: success()
        run: |
          image=ghcr.io/pdreker/fritzbox_exporter
          tag=${{ steps.update_semver.outputs.tag }}
          echo ${{secrets.GHCR_PAT }} | docker login -u pdreker --password-stdin ghcr.io
          docker build -t $image:$tag .
          docker push $image:$tag