name: Run Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  run-checks:
    runs-on: ubuntu-latest
    name: Run Flake8 linter
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint with flake8
        id: flake8
        continue-on-error: true
        run: |
          flake8 . | tee lint.log
          rescode=${PIPESTATUS[0]}
          echo "::set-output name=lint::$(cat lint.log)"
          exit $rescode
      - name: Run pytest
        id: pytest
        continue-on-error: true
        run: |
          python -m pytest . | tee test.log
          rescode=${PIPESTATUS[0]}
          echo "::set-output name=tests::$(cat test.log)"
          exit $rescode
