name: Run Tests

on:
  pull_request:
    branches:
    - develop

jobs:
  run-flake8:
    runs-on: ubuntu-latest
    name: Run Flake8 linter
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      id: flake8
      continue-on-error: true
      run: |
        pipenv run lint | tee lint.log
        rescode=${PIPESTATUS[0]}
        echo "::set-output name=lint::$(cat lint.log)"
        exit $rescode

  run-pytest:
    runs-on: ubuntu-latest
    name: Run PyTest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Run pytest
      id: pytest
      continue-on-error: true
      run: |
        pipenv run test | tee test.log
        rescode=${PIPESTATUS[0]}
        echo "::set-output name=tests::$(cat test.log)"
        exit $rescode
